### ISSUE TITLE
the environment of the project

### ISSUE THREAD

**Issue by alickzhu** [oguzserbetci/argmin2017#1]
HI, I recently read the paper 'Here's my Point: Joint Pointer Architecture for Argument Mining' and I find your implement. Thanks for that ! But I have difficult when I try to run the code with Keras. I guess there is something wrong with the environment configuration.
could you please tell me your version of TensorFlow and Keras ?
thanks !

**Comment by oguzserbetci** [comment]
Hey, Pipfile.lock is in [pytorch-impl branch](https://github.com/oguzserbetci/argmin2017/tree/pytorch-impl/keras) I will update the master branch to have it as well, when I get around to it. Sorry I pushed to the wrong branch earlier. Let me know if it works :)
